ntimepoints:
  - 3
  - 5
  - 7

nseeds: 20

ncells_readcount: 100
threshold_readcount: 0.167

error_rate_readcount:
  - 0.01
  - 0.025
  - 0.05
  - 0.075
  - 0.10


estimated_fp: 0.13
estimated_fn: 0.16

read_depth: 30
ado: 15

mutation_tree: 'adversarial_tree.csv'
nmutations: 5

SCITE_installation: '/n/fs/ragr-data/users/palash/SCITE/scite'
SPhyR_installation: '/n/fs/ragr-data/users/palash/SPhyR/build/kDPFC'
COMPASS_installation: '/n/fs/ragr-data/users/aj7381/COMPASS/COMPASS'
PhyloVar_installation: '/n/fs/ragr-data/users/aj7381/Phylovar/src/phylovar.py'
