ntimepoints:
  - 3
  - 4
  - 5

nmutations: 10

nseeds: 50

ncells_readcount: 
  - 100

ncells_limited:
  - 100

threshold_readcount: 0.05

error_rate_readcount:
  - 0.01
  - 0.05
  - 0.10
  - 0.20
  - 0.40


estimated_fp: 0.13
estimated_fn: 0.12

read_depth: 30
ado: 15

mutation_tree: 'adversarial_tree.csv'

SCITE_installation: '/n/fs/ragr-data/users/palash/SCITE/scite'
SPhyR_installation: '/n/fs/ragr-data/users/palash/SPhyR/build/kDPFC'
COMPASS_installation: '/n/fs/ragr-data/users/aj7381/COMPASS/COMPASS'
PhyloVar_installation: '/n/fs/ragr-data/users/aj7381/Phylovar/src/phylovar.py'
sclongtree_installation: '/n/fs/ragr-research/users/aj7381/sc_longitudinal_infer/algorithm/selectBestTree.py'
lace_installation: '/n/fs/ragr-research/users/aj7381/sc_longitudinal_infer/LACE_exp/run_LACE.R'
lace_output_installation: '/n/fs/ragr-research/users/aj7381/sc_longitudinal_infer/LACE_exp/read_LACE_inference.R'
bnpc_installation: '/n/fs/ragr-research/users/aj7381/BnpC/run_BnpC.py'
Rdata_conversion_script: '/n/fs/ragr-research/users/aj7381/sc_longitudinal_infer/simulation/convertCSVToRData.R'



